spring:
  h2:
    console.enabled: true #pour afficher la console H2
    console.path: /h2-console
  datasource:
    url: jdbc:h2:mem:WEB #url de la base de données
    driverClassName: org.h2.Driver #driver h2
    username: sa #username
    password: password
  jpa:
    show-sql: true # affiche les logs sql
    properties:
      hibernate:
        format_sql: true # format les logs sql
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # creer les tables si elles n'existent pas, sinon les mettre à jour